USE [master]
GO

/****** Object:  Database [ NICS_Survey]    Script Date: 14/10/2015 14:32:17 ******/
DROP DATABASE [ NICS_Survey]
GO

/****** Object:  Database [ NICS_Survey]    Script Date: 14/10/2015 14:32:17 ******/
CREATE DATABASE [ NICS_Survey]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N' NICS_Survey', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ NICS_Survey.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N' NICS_Survey_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ NICS_Survey_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ NICS_Survey] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ NICS_Survey].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ NICS_Survey] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ NICS_Survey] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ NICS_Survey] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ NICS_Survey] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ NICS_Survey] SET ARITHABORT OFF 
GO

ALTER DATABASE [ NICS_Survey] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ NICS_Survey] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ NICS_Survey] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ NICS_Survey] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ NICS_Survey] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ NICS_Survey] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ NICS_Survey] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ NICS_Survey] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ NICS_Survey] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ NICS_Survey] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ NICS_Survey] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ NICS_Survey] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ NICS_Survey] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ NICS_Survey] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ NICS_Survey] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ NICS_Survey] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ NICS_Survey] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ NICS_Survey] SET RECOVERY FULL 
GO

ALTER DATABASE [ NICS_Survey] SET  MULTI_USER 
GO

ALTER DATABASE [ NICS_Survey] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ NICS_Survey] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ NICS_Survey] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ NICS_Survey] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ NICS_Survey] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ NICS_Survey] SET  READ_WRITE 
GO


