//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyID { get; set; }
        public string SurveyTitle { get; set; }
        public Nullable<System.DateTime> SurveyStartDate { get; set; }
        public Nullable<System.DateTime> SurveyEndDate { get; set; }
        public Nullable<int> SurveyCreatorID { get; set; }
        public string SurveyStartSummary { get; set; }
        public string SurveyEndSummary { get; set; }
    }
}
